# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BCB Lab
email: benilton@unicamp.br
description: > # this means to ignore newlines until "baseurl:"
  Code back-end for BCB Lab by Benilton Carvalho / Universidade de Campinas / UNICAMP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labbcb.github.io" # the base hostname & protocol for your site
twitter_username: bcb_lab
github_username:  labbcb

# Build settings
markdown: kramdown
exclude: ['*.Rmd']

encoding: UTF-8
