# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Métodos Computacionais em Estatística
email: benilton@unicamp.br
description: > # this means to ignore newlines until "baseurl:"
  Disciplina "Métodos Computacionais em Estatística"  produzido por Benilton Carvalho / Universidade de Campinas / UNICAMP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://estatcomp.github.io" # the base hostname & protocol for your site
twitter_username: benilton
github_username:  estatcomp

# Build settings
markdown: kramdown
exclude: ['*.Rmd']

encoding: UTF-8

